---
- name: '[OCP4-AUTO-INSTALL] Deploy an Openshift4 cluster'
  hosts: localhost
  connection: local
  vars_files:
    - vars/vars.yml
    - vault/vault.yml
  tasks:
    - name: '[OCP4-AUTO-INSTALL][PREREQS] Prerequisites for the installation'
      include_role:
        name: "{{ roleitem.rolename }}"
      loop:
        - { rolename: common }
        - { rolename: awscli }
        - { rolename: vmw-prepare-certs, vCenterCACerts: "{{ auto_vcenter_ca_certs }}" }
      loop_control:
        loop_var: roleitem
      when: roleitem.vCenterCACerts | default('True') | bool

      when:
        - only_post_install != True
        - prereqs == True

    - name: '[OCP4-AUTO-INSTALL][INSTALL] Installation of the OCP4 Cluster'
      include_role:
        name: "ocp4-install"
      when:
        - only_post_install != True
