---
configure_tower_credential_types:
  - name: "OCP4 Pull Secrets"
    description: "Credential Type to store OCP4 Pull Secrets"
    kind: "cloud"
    inputs:
      fields:
        - id: ocp4_pull_secret
          type: string
          label: OCP4 Pull Secret
          secret: true
          help_text: >-
            Get the pull secret from https://cloud.redhat.com/openshift/install/pull-secret
            to authenticate downloading container images for OpenShift Container Platform
            components from services such as Quay.io.
      required:
        - ocp4_pull_secret
    injectors:
      env:
        OCP4_PULL_SECRET: !unsafe '{{ ocp4_pull_secret }}'
  - name: "htpasswd"
    description: "Credential Type to store htpassws credentials"
    kind: "cloud"
    inputs:
      fields:
        - id: username
          type: string
          label: Username
          secret: false
          help_text: >-
            Enter the Username for the htpasswd credential
        - id: password
          type: string
          label: Passwd
          secret: true
          help_text: >-
            Enter the Password for the htpasswd credential
      required:
        - username
        - password
    injectors:
      env:
        HTPASSWD_USERNAME: !unsafe '{{ username }}'
        HTPASSWD_PASSWORD: !unsafe '{{ password }}'
...
