---

- name: '[POSTINSTALL][INFRA-NODES] Grab some global cluster trivia for git to use'
  k8s_facts:
    kubeconfig: "{{ kubeconfig }}"
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: infradata

- name: '[POSTINSTALL][INFRA-NODES] Deploy Infra EFK Nodes MachineSet'
  include_role:
    # name: machineset
    name: ocp4-post-machinesets
  vars:
    instance_type: r5.xlarge
    node_labels:
      - "{{ infra_label }}"
      - "{{ infra_label }}-efk"
    zone_suffixes:
      - a
      - b
      - c
    name_identifier: "{{ infra_label }}"

- name: '[POSTINSTALL][INFRA-NODES] Wait for Elasticsearch Nodes to be available'
  when: _infra_node_elasticsearch_nodes | d(False) | bool
  k8s_facts:
    api_version: v1
    kind: Node
    label_selectors:
    - node-role.kubernetes.io/elasticsearch =
  register: r_es_nodes
  until:
  - r_es_nodes.resources | length | int == _infra_node_elasticsearch_replicas | int
  delay: 30
  retries: 15
